Add rc.local config for binding dpdk port after reboot
linkernetworks/vortex pull request #212
Opened 2018-08-01 06:32 UTC by sufuf3

2018-08-01 06:47 UTC, John-Lin commented
加一下註解

2018-08-01 09:42 UTC, sufuf3 commented
會再繼續研究用 systemd
好了的話，會再送另外的 PR 。

2018-08-01 17:03 UTC, John-Lin commented on developers/Vagrantfile
> +echo 'export IFnum=enp0s8' | sudo tee -a /root/.bashrc
`IFDRV ` 跟 `IFnum` 其實沒用到？

2018-08-01 17:08 UTC, sufuf3 commented on developers/Vagrantfile
> +echo 'export IFnum=enp0s8' | sudo tee -a /root/.bashrc
喔 對的 
這就拿掉他們

2018-08-01 17:19 UTC, John-Lin commented on developers/systemctl/dpdkbind.service
> +After=network-pre.target multi-user.target
multi-user.target 為什麼要在 dpdkbind.service 之後呀?

2018-08-02 00:14 UTC, sufuf3 commented on developers/systemctl/dpdkbind.service
> +After=network-pre.target multi-user.target
恩～這邊沒有特別研究。
不過我把 `network-pre.target` 拿掉了
因為原本的寫法， reboot 後，不能 vagrant ssh 。拿掉就可以了～ 
然後重新進到 VM 中，也有看到 dpdk 的 port 有綁定了。

2018-08-06 08:53 UTC, sufuf3 commented
這個 PR 測過是 OK 的。
重開機後 (vagrant halt) 也綁好了。

2018-08-06 09:08 UTC, John-Lin requested changes

2018-08-06 09:08 UTC, John-Lin commented on developers/Vagrantfile
> +echo 'NET_IF_NAME=enp0s18' | sudo tee -a /etc/default/dpdkbind
`echo 'NET_IF_NAME='${NET_IF_NAME} | sudo tee -a /etc/default/dpdkbind`

2018-08-06 09:11 UTC, sufuf3 commented on developers/Vagrantfile
> +echo 'NET_IF_NAME=enp0s18' | sudo tee -a /etc/default/dpdkbind
Done

2018-08-06 09:12 UTC, John-Lin approved these changes

2018-08-06 10:02 UTC, WakeupTsai approved these changes

2018-08-06 17:26 UTC, merged