[Task] VX-271: Log handler which responses the logs of the containers
linkernetworks/vortex pull request #258
Opened 2018-08-17 09:54 UTC by WakeupTsai

2018-08-18 05:59 UTC, John-Lin requested changes

2018-08-18 05:59 UTC, John-Lin commented on src/server/handler_log.go
> +		fmt.Errorf("failed to get the details of node: %v", err)
should response 500 here

2018-08-18 08:24 UTC, John-Lin commented on src/kubernetes/containers.go
> +func (kc *KubeCtl) GetContainer(name string, podname string, namespace string) (*corev1.Container, error) {
This function seems not to be used?

2018-08-22 04:11 UTC, John-Lin approved these changes

2018-08-22 04:13 UTC, John-Lin approved these changes

2018-08-22 08:25 UTC, hwchiu approved these changes

2018-08-22 08:31 UTC, merged